import { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Bem vindos ao Next.js!</h1>

        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Mollitia,
           at provident, voluptatem nulla error natus quam hic incidunt, corporis
            repudiandae necessitatibus deserunt. Cumque corporis pariatur quibusdam 
            ea corrupti, quam blanditiis.
        </p>
      </main>
    </>
  );

}

export default Home